plugins {
    id 'com.android.library'
    id 'com.vanniktech.maven.publish'
}

android {
    namespace 'io.github.luisgamas.simplecalendar'
    compileSdk 36

    defaultConfig {
        minSdk 26
        targetSdk 36

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.14.0'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.16.1'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test:rules:1.7.0'
}

mavenPublishing {
    publishToMavenCentral()

    signAllPublications()

    coordinates(
        "${project.findProperty("GROUP") ?: "io.github.luisgamas"}",
        "${project.findProperty("POM_ARTIFACT_ID") ?: "simplecalendar"}",
        "${project.findProperty("VERSION_NAME") ?: "1.0.0"}"
    )

    pom {
        name.set(project.findProperty("POM_NAME") ?: "SimpleCalendar")
        description.set(project.findProperty("POM_DESCRIPTION") ?: "A highly customizable Android calendar widget.")
        inceptionYear.set(project.findProperty("POM_INCEPTION_YEAR") ?: "2023")
        url.set(project.findProperty("POM_URL") ?: "https://github.com/luisgamas/SimpleCalendar")

        licenses {
            license {
                name.set(project.findProperty("POM_LICENSE_NAME") ?: "MIT")
                url.set(project.findProperty("POM_LICENSE_URL") ?: "https://opensource.org/license/mit/")
                distribution.set(project.findProperty("POM_LICENSE_DIST") ?: "repo")
            }
        }

        developers {
            developer {
                id.set(project.findProperty("POM_DEVELOPER_ID") ?: "LuisGamas")
                name.set(project.findProperty("POM_DEVELOPER_NAME") ?: "Luis Donaldo Gamas")
                url.set(project.findProperty("POM_DEVELOPER_URL") ?: "https://github.com/luisgamas")
            }
        }

        scm {
            url.set(project.findProperty("POM_SCM_URL") ?: "https://github.com/luisgamas/SimpleCalendar")
            connection.set(project.findProperty("POM_SCM_CONNECTION") ?: "scm:git:git://github.com/luisgamas/SimpleCalendar.git")
            developerConnection.set(project.findProperty("POM_SCM_DEV_CONNECTION") ?: "scm:git:ssh://git@github.com/luisgamas/SimpleCalendar.git")
        }
    }
}




